### ISSUE TITLE
DRY

### ISSUE THREAD

**Issue by ghost** [h237huan/prj-rev-bwfs-dasmoto#5]
https://github.com/h237huan/prj-rev-bwfs-dasmoto/blob/master/HELLO%20CSS/RESOURCE/index.css#L15-L35

These CSS rules are extremely repetitive. Try putting shared styles into a single rule that selects multiple sections, and put the more unique styles (the color basically) into their own rules.

Here's how you might do this for font-family:

```css
h1, h2, span, p {
  font-family: Helvetica;
}
```
